# numpy

In [ ]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)
# suppress=True 를 통해 숫자를 지수 표현이 아닌 숫자 표현이 가능
# precision 에 숫자를 입력하여 소수점 자리수 설정
import matplotlib.pyplot as plt

In [ ]:
np.random.seed(42)
np.random.rand(5)

array([0.3745, 0.9507, 0.732 , 0.5987, 0.156 ])

In [ ]:
np.random.seed(1)
np.random.rand(5)

array([0.417 , 0.7203, 0.0001, 0.3023, 0.1468])

In [ ]:
np.random.seed(42)
np.random.rand(5)

array([0.3745, 0.9507, 0.732 , 0.5987, 0.156 ])

In [ ]:
# 성능 차이를 확인하기 위해 1백만 개의 정수를 저장하는 넘파이 배열과 리스트를 비교
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]
# 넘파이 배열이 리스트보다 수십, 수백배 정도 더 빠르고 메모리도 적게 사용

1.15 ms ± 104 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
86.9 ms ± 20.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
86.9/1.15
# 약 75배 빠름

75.56521739130436

# ndarray 생성

## 1차원 배열

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
type(arr1)
# ndarray = n 차원 배열

numpy.ndarray

In [ ]:
list1 = [2,4,3,1]
type(list1)

list

In [ ]:
# 서로 다른 자료형이기 때문에 같은 연산을 적용해도 다르게 작동할 수 있음
print(arr1 * 2) # 각 요소마다 연산 적용
print(list1 * 2) # 리스트 반복

[12. 15. 16.  0.  2.]
[2, 4, 3, 1, 2, 4, 3, 1]


In [ ]:
print(arr1 * 2) # 각 요소마다 연산 적용

[12. 15. 16.  0.  2.]


In [ ]:
# 배열 차원의 크기
arr1.shape
# 열
# 1 * 5

(5,)

In [ ]:
arr1.ndim
# 행 1

1

In [ ]:
# 배열에 저장된 자료형
arr1.dtype

dtype('float64')

## 2차원 배열

In [ ]:
# 2차원
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
type(arr2)
# ndarray = n 차원 배열

numpy.ndarray

In [ ]:
# 각 요소마다 연산 적용
arr2 * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
# 같은 위치의 값끼리 연산
arr2 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [ ]:
# 배열 차원의 크기
arr2.shape
# 행 열
# 2 * 4

(2, 4)

In [ ]:
arr2.ndim
# 행 2

2

In [ ]:
# 배열에 저장된 자료형
arr2.dtype

dtype('int64')

## 3차원 배열

In [ ]:
# 3차원
data3 = [
         [[1, 2, 3, 4], [5, 6, 7, 8]],
         [[1, 2, 3, 4], [5, 6, 7, 8]],
         [[1, 2, 3, 4], [5, 6, 7, 8]]
        ]
arr3 = np.array(data3)
arr3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [ ]:
type(arr3)
# ndarray = n 차원 배열

numpy.ndarray

In [ ]:
# 각 요소마다 연산 적용
arr3 * 10

array([[[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [ ]:
# 같은 위치의 값끼리 연산
arr3 + arr3

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16]]])

In [ ]:
# 배열 차원의 크기
arr3.shape
# 층 행 열
# 3 * 2 * 4

(3, 2, 4)

In [ ]:
arr3.ndim
# 층 3

3

In [ ]:
# 배열에 저장된 자료형
arr3.dtype

dtype('int64')

## array 관련 함수

In [ ]:
# 0 이 들어 있는 배열
# 배열의 형태를 직접 지정
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# 0 이 들어 있는 배열
# 기존 배열을 기반으로 새로운 배열 생성
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
np.zeros_like(arr1)

array([0., 0., 0., 0., 0.])

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# zeros, zeros_like 와 동일하지만 내용을 1 로 채우는 배열
# 배열의 형태를 직접 지정
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# zeros, zeros_like 와 동일하지만 내용을 1 로 채우는 배열
# 기존 배열을 기반으로 새로운 배열 생성
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
np.ones_like(arr1)

array([1., 1., 1., 1., 1.])

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# ones 와 비슷하게 1 이 들어 있는 배열을 만들지만, 대각선 방향으로 채움 = 단위행렬
np.eye(3, 6)
# 기본값이 첫 번째 열부터 시작

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [ ]:
np.eye(3, 6, 2)
# 3 번째 입력하는 숫자 - 세 번째 열부터 시작하게 설정

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [ ]:
# 초기화되지 않은 배열 = ones 나 zeros 처럼 값을 초기화하지 않음
# 초기화되지 않은 메모리를 반환하기 때문에 0 이 아닌 가비지 값을 포함할 수 있음
# 데이터를 새로 채우기 위해 배열을 생성하는 경우에 사용할 것
# 배열의 형태를 직접 지정
np.empty((2, 3, 2))

array([[[4.6472e-310, 0.0000e+000],
        [0.0000e+000, 0.0000e+000],
        [6.8619e-310, 1.5001e+248]],

       [[4.3117e-096, 1.1600e-028],
        [3.7778e+180, 1.1600e-028],
        [4.1946e+228, 1.5554e+161]]])

In [ ]:
# 초기화되지 않은 배열 = ones 나 zeros 처럼 값을 초기화하지 않음
# 기존 배열을 기반으로 새로운 배열 생성
data3 = [
         [[1, 2, 3, 4], [5, 6, 7, 8]],
         [[1, 2, 3, 4], [5, 6, 7, 8]],
         [[1, 2, 3, 4], [5, 6, 7, 8]]
        ]
arr3 = np.array(data3)
np.empty_like(arr3)

array([[[     96910628987983,                   0, 8246760659587506286,
         7957614690910108001],
        [2335244403110605669, 7953674036962224243, 8007511671213138020,
         3347429548792291430]],

       [[7815265016535326730, 4188459165459177324, 2336931105441403424,
         8241904490239631457],
        [7526756837609791858, 8007511670809719584, 2338623232261300326,
         8583971276541684070]],

       [[8461244959900071017, 8800068994230529637, 5917793821414879845,
         2333181740693419109],
        [7021800530506114414, 7956018259993763961, 8315181395361538151,
         8030592660759606304]]])

In [ ]:
# range 함수의 배열 버전
np.arange(15) # 시작번호 생략 = 처음부터

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(0, 10)
# 시작번호, 끝번호
# 끝번호 포함하지 않음

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10, 2)
# 시작번호, 끝번호, 증가값
# 증가값 즉, 간격을 만들어 배열 생성

array([0, 2, 4, 6, 8])

In [ ]:
# 등분하는 배열
np.linspace(0, 10, 5)
# 시작번호, 끝번호, 등분의 개수
# 끝번호 포함

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 자료형

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr2.dtype

dtype('int32')

## 명시적으로 변환

In [ ]:
# 명시적으로 변환 가능(int64 -> float64)
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
# astype
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [ ]:
float_arr.dtype

dtype('float64')

In [ ]:
# float64 -> int64
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.astype(np.int32)
# 소수점 아래 자리는 버려짐

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
arr = arr.astype(np.int32)
arr.dtype

dtype('int32')

## 숫자 형태의 문자열을 담고 있는 배열

In [ ]:
# 숫자 형태의 문자열을 담고 있는 배열
# string_ 는 고정된 크기를 가지므로 경고 없이 임의로 잘라낼 수 있어 사용에 주의
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.dtype
# 길이가 4

dtype('S4')

In [ ]:
numeric_strings = numeric_strings.astype(float)
numeric_strings.dtype
# 문자열 -> 숫자 변환
# float64 대신 float 만 사용해도 알맞은 자료형으로 변환

dtype('float64')

In [ ]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [ ]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.unicode_)
numeric_strings

array(['1.25', '-9.6', '42'], dtype='<U4')

## 다른 배열의 속성 사용

In [ ]:
# 다른 배열의 속성 사용 가능
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
int_array.dtype

dtype('int64')

In [ ]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [ ]:
calibers.dtype

dtype('float64')

In [ ]:
int_array = int_array.astype(calibers.dtype)
int_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
int_array.dtype

dtype('float64')

## dtype 코드

In [ ]:
# dtype 코드 사용 가능
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

# 산술 연산

In [ ]:
# 크기가 동일한 배열 간의 산술 연산은 배열의 각 요소 단위로 적용
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [ ]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
# 크기가 동일한 배열 간의 비교 연산
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
print(arr)
arr2 > arr

[[1. 2. 3.]
 [4. 5. 6.]]


array([[False,  True, False],
       [ True, False,  True]])

# 인덱싱, 슬라이싱

## 1차원 배열

In [ ]:
# 1차원 배열
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8] = 12
arr
# 브로드캐스팅 = 크기가 다른 배열 간의 연산
# 12 라는 스칼라 값이 선택 영역 전체로 전파되었다고 해서 브로드캐스팅이라고 표현
# 원본 변경

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## 배열 슬라이스 생성

In [ ]:
# 배열 슬라이스 생성
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
# 원본 변경
arr_slice[1] = 12345
arr
# 원본 배열에서 배열 슬라이스는 5 번 인덱스부터 7 번 인덱스
# 배열 슬라이스 = 5 번 인덱스부터 7 번 인덱스에서 1 번 인덱스(= 6 번 인덱스)인 12 가 12345 로 변경

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
# 시작 번호와 끝 번호를 생략하면 전체(처음부터 끝까지)
arr_slice[:] = 64
arr
# 배열 슬라이스 = 5 번 인덱스부터 7 번 인덱스에 있는 값이 모두 64 로 변경

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## 배열 슬라이스를 복사하여 생성

In [ ]:
# 배열 슬라이스를 복사하여 생성
arr_slice = arr[5:8].copy()
arr_slice

array([64, 64, 64])

In [ ]:
# 원본 변경 안됨
arr_slice[1] = 12345
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr_slice
# 복사본에서만 변경이 되었음

array([   64, 12345,    64])

In [ ]:
# 시작 번호와 끝 번호를 생략하면 전체(처음부터 끝까지)
arr_slice[:] = 32
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr_slice

array([32, 32, 32])

## 다차원 배열을 다루는 옵션

In [ ]:
# 다차원 배열을 다루는 옵션
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[0]

array([1, 2, 3])

In [ ]:
# 개별 원소에 접근하기 위해서 재귀적으로 접근해야 함, 즉 대괄호 한 번 더 사용
arr2d[0][2]

3

In [ ]:
# 대괄호를 한 번 더 쓰는 작업이 번거롭다면 쉼표로 구분된 리스트로도 같은 결과 얻을 수 있음
arr2d[0, 2]

3

In [ ]:
# 2 * 2 * 3 배열
arr3d = np.array([
                  [[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]
                  ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d.shape
# 2 깊이 2 행 3 열

(2, 2, 3)

In [ ]:
arr3d[0] # 1 번째 깊이

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 스칼라 값 할당
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# 배열 할당
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[1, 0] # 2 번째 깊이 & 1 번째 행
# 아래에서 인덱싱 2번한 결과와 동일

array([7, 8, 9])

In [ ]:
x = arr3d[1] # 2 번째 깊이
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x[0]

array([7, 8, 9])

## 슬라이스로 선택

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]
# 두 번째 행까지 선택

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2, 1:]
# 두 번째 행까지 & 두번째 열부터 끝까지

array([[2, 3],
       [5, 6]])

In [ ]:
# 정수 인덱스와 슬라이스를 함께 사용
lower_dim_slice = arr2d[1, :2]
lower_dim_slice
# 두 번째 행 & 두 번째 열까지

array([4, 5])

In [ ]:
lower_dim_slice.shape
# 2차원 배열이 1차원으로
# 1 * 2

(2,)

In [ ]:
arr2d[:2, 2]
# 두 번째 행까지 & 세 번째 열

array([3, 6])

In [ ]:
arr2d[:, :1]
# 전체 행 & 첫 번째 열까지
# 원래 차원 = 2차원

array([[1],
       [4],
       [7]])

In [ ]:
arr2d[:2, 1:] = 0
arr2d
# 두 번째 행까지 & 두 번째 열부터 끝까지 범위 선택하여 값을 할당

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# 불 값으로 선택

In [ ]:
# 불 인덱스
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names
# 축의 길이가 7개

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data = np.array([[4, 7],
                 [0, 2],
                 [-5, 6],
                 [0, 0],
                 [1, 2],
                 [-12, -4],
                 [3, 4]])
data
# 축의 길이가 7개

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names == "Bob"]
# 불 배열은 반드시 인덱싱하는 축의 길이가 동일해야 함
# True 에 해당하는 축이 선택

array([[4, 7],
       [0, 0]])

In [ ]:
data[names == "Bob", 1:]
# 열도 함께 선택 = 두 번째 열
# 2차원

array([[7],
       [0]])

In [ ]:
data[names == "Bob", 1]
# 열도 함께 선택 = 두 번째 열
# 1차원

array([7, 0])

In [ ]:
names != "Bob"
# 부정의 의미 = 같지 않다
# 같지 않으면 참

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
~(names == "Bob")
# 부정의 의미 = 같지 않다
# 같지 않으면 참

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
data[~(names == "Bob")]
# 부정의 의미로 인덱싱
# True 에 해당하는 축이 선택

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
cond = names == "Bob"
cond
# 불 인덱스를 저장

array([ True, False, False,  True, False, False, False])

In [ ]:
data[~cond]
# 부정의 의미로 인덱싱
# 참 거짓이 반대로 바뀌어 인덱싱

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
# And (&) OR (|)
mask = (names == "Bob") | (names == "Will")
mask
# OR = 둘 중 하나만 만족해도 참, 둘 다 만족해도 참
# = 이름 2개 선택

array([ True, False,  True,  True,  True, False, False])

In [ ]:
data[mask]
# OR 인덱싱

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [ ]:
# [  4,   7],
# [  0,   2],
# [ -5,   6],
# [  0,   0],
# [  1,   2],
# [-12,  -4],
# [  3,   4]

In [ ]:
# 비교 연산자
data[data < 0] = 0
data
# data 에 저장된 음수를 0 으로 변경

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [ ]:
# [4, 7],
# [0, 2],
# [0, 6],
# [0, 0],
# [1, 2],
# [0, 0],
# [3, 4]

In [ ]:
names != "Joe"

array([ True, False,  True,  True,  True, False, False])

In [ ]:
data[names != "Joe"] = 7
data
# 이름이 Joe 가 아닌 경우 7 로 변경

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

# 팬시 인덱싱

In [ ]:
# 정수 배열을 사용한 인덱싱
arr = np.zeros((8, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(8):
    arr[i] = i
arr
# 1 ~ 7 정수 순서대로 행의 하위집합을 선택하여 할당

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
arr[[4, 3, 0, 6]]
# 정수로 특정 행을 선택하여 인덱싱 = 팬시 색인

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [ ]:
arr[[-3, -5, -7]]
# 음수로 인덱싱하면 반대로 작동 = 팬시 색인
# -8 ~ -1
# 6 번째 행, 4 번째 행, 2 번째 행

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr
# 0 ~ 31 정수를 가진 8 행 * 4 열을 배열로 재구성

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
# 각 위치에 대응하는 1차원 배열이 선택
# 2 번째 행 & 1 번째 열
# 6 번째 행 & 4 번째 열
# 8 번째 행 & 2 번째 열
# 3 번째 행 & 3 번째 열

array([ 4, 23, 29, 10])

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
# 2 번째, 6 번째, 8 번째, 3 번째 행을 선택
# 열 순서를 0, 3, 1, 2 열로 바꿔 2차원 배열이 선택

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr
# 각 위치에 대응하는 1차원 배열이 선택
# 2 번째 행 & 1 번째 열
# 6 번째 행 & 4 번째 열
# 8 번째 행 & 2 번째 열
# 3 번째 행 & 3 번째 열에 해당하는 값을 0 으로 할당

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

# 배열 재구성

In [ ]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.reshape((4, 2))
# 4 * 2 형태의 배열로 재구성

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr
# 원본 변경이 안된 것을 보아 복사본 반환하는 것을 알 수 있음

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.reshape((4, 2), order = 'C')
# 행 우선 정렬 = 기본값

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr.reshape((4, 2), order = 'F')
# 열 우선 정렬

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
arr.reshape((4, 2)).reshape((2, 4))
# 다차원 배열 재구성

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(15)
arr.reshape((5, -1))
# -1 를 사용하면 원본 데이터를 참조하여 적절한 값을 추론 = 여기서는 3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
other_arr = np.ones((3, 5))
other_arr.shape
# 배열의 차원

(3, 5)

In [ ]:
arr.reshape(other_arr.shape)
# 다른 배열의 차원을 바로 입력 가능

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr.ravel()
# 평탄화 = 다차원 배열을 낮은 차원으로 변환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr = np.arange(15).reshape((5, 3))
print(arr)
arr_after = arr.ravel()
arr_after[0] = 33
print(arr)
print(arr_after)
# 복사본 생성 안함 = 원본 변경

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[33  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[33  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr.flatten()
# 평탄화 = 다차원 배열을 낮은 차원으로 변환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr = np.arange(15).reshape((5, 3))
print(arr)
arr_after = arr.flatten()
arr_after[0] = 33
print(arr)
print(arr_after)
# 복사본 반환 = 복사본 생성하여 변경

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[33  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr.reshape((-1))
# 다차원 배열을 1차원 배열로 재구성

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.ravel('C')
# 평탄화 = 행 우선 정렬 방식

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.ravel('F')
#  평탄화 = 열 우선 정렬 방식

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

# 배열 이어 붙이고 나누기

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr1, arr2], axis=0)
# 위아래로 붙이기

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([arr1, arr2], axis=1)
# 좌우로 붙이기

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.vstack((arr1, arr2))
# 위아래로 붙이기

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((arr1, arr2))
# 좌우로 붙이기

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
arr = np.arange(10).reshape((5, 2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
first, second, third = np.split(arr, [1, 3])
first
# 1 번 행 기준, 3 번 행 기준으로 분할

array([[0, 1]])

In [ ]:
second

array([[2, 3],
       [4, 5]])

In [ ]:
third

array([[6, 7],
       [8, 9]])

# 배열 전치와 축 바꾸기

In [ ]:
# 배열 전치
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T
# 행과 열을 바꿔 반환

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
# 행렬의 내적 = 행렬 곱
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
# 5 * 3

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr.T
# 3 * 5

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [ ]:
np.dot(arr.T, arr)
# 행렬의 내적 = 행렬 곱 = 앞 배열의 행과 뒤 배열의 열의 각 대응하는 값을 곱하여 더하는 것
# 첫 번째 행과 첫 번째 열
# 첫 번째 행과 두 번째 열
# 첫 번째 행과 세 번째 열
# 두 번째 행과 첫 번째 열
# 두 번째 행과 두 번째 열
# 두 번째 행과 세 번째 열
# 세 번째 행과 첫 번째 열
# 세 번째 행과 두 번째 열
# 세 번째 행과 세 번째 열
# 순차적으로 동일하게 연산
# 행렬 곱은 두 행렬의 대응하는 차원의 원소 수가 같아야 함
# 3 * 5 * 5 * 3
# 5 로 일치함

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [ ]:
# 예) 앞 배열의 첫 번째 행과 뒤 배열의 첫 번째 열의 각 대응하는 값을 곱하여 더하는 것
0,  1,  6, -1,  1 # 앞 배열의 첫 번째 행
0,  1,  6, -1,  1 # 뒤 배열의 첫 번째 열
0 * 0 + 1 * 1 + 6 * 6 + -1 * -1 + 1 * 1

39

In [ ]:
# 첫 번째 행과 두 번째 열
0,  1,  6, -1,  1 # 앞 배열의 첫 번째 행
1,  2,  3,  0,  0 # 뒤 배열의 두 번째 열
0 * 1 + 1 * 2 + 6 * 3 + -1 * 0 + 1 * 0

20

In [ ]:
arr.T @ arr
# 행렬 곱을 수행하는 다른 방법

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [ ]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
# 2차원 배열 = 5(2차원의 축 = 0) * 3(1차원의 축 = 1)
arr.swapaxes(0, 1)
# swapaxes 메서드를 통해 2 개의 축 번호를 받아서 배열을 바꿈
# 배열 전치 T 와 동일한 결과 볼 수 있음

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [ ]:
arr.swapaxes(1, 0)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [ ]:
arr.swapaxes(0, 0)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr.swapaxes(1, 1)

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
# 3차원 배열 = 2(3차원의 축 = 0) * 3(2차원의 축 = 1) * 4(1차원의 축 = 2)
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr.swapaxes(0, 1)
# 3 * 2 * 4

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [ ]:
arr.swapaxes(0, 2)
# 4 * 3 * 2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [ ]:
arr.swapaxes(1, 2)
# 2 * 4 * 3

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [ ]:
# 3차원 배열 = 2(3차원의 축 = 0) * 3(2차원의 축 = 1) * 4(1차원의 축 = 2)
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr.transpose((1,0,2))
# 3 * 2 * 4

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [ ]:
arr.transpose((2,1,0))
# 4 * 3 * 2

array([[[0],
        [3]],

       [[1],
        [4]],

       [[2],
        [5]]])

In [ ]:
arr.transpose((0,2,1))
# 2 * 4 * 3

array([[[0, 3],
        [1, 4],
        [2, 5]]])

# 난수 생성

In [ ]:
# 표준정규분포
samples = np.random.standard_normal(size=(4, 4))
samples

array([[ 1.30370091, -0.92297611,  0.56740617,  0.80906929],
       [-1.07606396,  2.31616863, -1.98839582,  0.14558736],
       [ 2.63788017,  0.29472759,  1.0271773 , -0.78874249],
       [-0.67732524,  1.21763277, -1.90789267,  1.0242447 ]])

In [ ]:
# 표준 모듈 random 과 넘파이 random 을 이용하여 표준정규분포 생성 속도 비교
from random import normalvariate
N = 1000000
# 파이썬 내장 random 모듈은 한 번에 하나의 값만 생성
%timeit samples = [normalvariate(0, 1) for _ in range(N)] # 평균 0 표준편차 1
# 넘파이 random 은 매우 큰 표본을 생성하지만 파이썬 표준 모듈보다 수십배 이상 빠름
%timeit np.random.standard_normal(N)

951 ms ± 274 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
34.2 ms ± 6.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
951 / 34.2
# 약 27 배 빠름

27.807017543859647

In [ ]:
# 난수 생성기를 명시적으로 설정
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
data

array([[-1.4238,  1.2637, -0.8707],
       [-0.2592, -0.0753, -0.7409]])

In [ ]:
type(rng)
# 난수 생성기 객체
# rng 를 가지고 난수 데이터 생성

numpy.random._generator.Generator

# 유니버설 함수

In [ ]:
# 배열의 각 원소를 빠르게 처리하는 함수
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)
# 제곱근

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)
# 지수함수
# 밑이 자연상수 e = 2.718
# 단항 유니버설 함수

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
# 이항 유니버설 함수
x = rng.standard_normal(8)
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [ ]:
y = rng.standard_normal(8)
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [ ]:
np.maximum(x, y)
# x 와 y 의 각 대응하는 값 중에서 최대값

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [ ]:
# 여러 개의 배열을 반환하는 유니버설 함수
arr = rng.standard_normal(7) * 5
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [ ]:
remainder, whole_part = np.modf(arr)
remainder # 나머지

array([ 0.51459671, -0.10791367, -0.7909463 ,  0.24741966, -0.71800536,
       -0.40843795,  0.62369966])

In [ ]:
whole_part # 몫

array([ 4., -8., -0.,  2., -6., -0.,  8.])

In [ ]:
# out 매개변수 사용
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [ ]:
out = np.zeros_like(arr)
out

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.add(arr, 1)
# arr 배열에 1 를 더한 배열 = 새로운 배열

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [ ]:
arr # 기존 배열에 변화 없음

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [ ]:
np.add(arr, 1, out=out)
# out 이라는 배열에 연산 결과를 할당

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [ ]:
out

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

# 배열 연산으로 조건부 표현

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result
# True 이면 x 값, False 이면 y 값으로 리스트 생성
# 리스트 컴프리헨션 문법은 순수 파이썬으로 수행하기 때문 큰 배열을 빠르게 처리 못함
# 다차원 배열에서 사용 불가능
# 넘파이 where 를 사용하면 아주 간결하게 작성 가능

[1.1, 2.2, 1.3, 1.4, 2.5]

In [ ]:
result = np.where(cond, xarr, yarr)
result
# 첫 번째 매개변수 - 조건
# 조건을 만족하면 두 번째 매개변수
# 조건을 만족하지 않으면 세 번째 매개변수
# True 이면 x 값, False 이면 y 값

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = rng.standard_normal((4, 4))
arr

array([[-1.3678,  0.6489,  0.3611, -1.9529],
       [ 2.3474,  0.9685, -0.7594,  0.9022],
       [-0.467 , -0.0607,  0.7888, -1.2567],
       [ 0.5759,  1.399 ,  1.3223, -0.2997]])

In [ ]:
arr > 0
np.where(arr > 0, 2, -2)
# 0 보다 크면 2, 나머지 - 2

array([[-2,  2,  2, -2],
       [ 2,  2, -2,  2],
       [-2, -2,  2, -2],
       [ 2,  2,  2, -2]])

In [ ]:
# 스칼라 값과 배열의 조합
np.where(arr > 0, 2, arr)
# 0 보다 크면 2, 나머지 원래 값

array([[-1.3678,  2.    ,  2.    , -1.9529],
       [ 2.    ,  2.    , -0.7594,  2.    ],
       [-0.467 , -0.0607,  2.    , -1.2567],
       [ 2.    ,  2.    ,  2.    , -0.2997]])

# 통계 메서드

In [ ]:
arr = rng.standard_normal((5, 4))
arr

array([[ 0.9029, -1.6216, -0.1582,  0.4495],
       [-1.3436, -0.0817,  1.7247,  2.6182],
       [ 0.7774,  0.8286, -0.959 , -1.2094],
       [-1.4123,  0.5415,  0.7519, -0.6588],
       [-1.2287,  0.2576,  0.3129, -0.1308]])

In [ ]:
arr.mean()
# 평균

0.018063390847970272

In [ ]:
np.mean(arr)
# 평균

0.018063390847970272

In [ ]:
arr.sum()
# 합계

0.36126781695940546

In [ ]:
arr.mean(axis=0) # 세로
# 각 열의 모든 행의 평균

array([-0.4609, -0.0151,  0.3345,  0.2137])

In [ ]:
np.mean([0.9029,-1.3436, 0.7774, -1.4123, -1.2287])
# 첫 번째 열의 모든 행의 평균

-0.46086

In [ ]:
arr.mean(axis=1) # 가로
# 각 행의 모든 열의 평균

array([-0.1068,  0.7294, -0.1406, -0.1944, -0.1973])

In [ ]:
np.mean([0.9029, -1.6216, -0.1582,  0.4495])
# 첫 번째 행의 모든 열의 평균

-0.10684999999999997

In [ ]:
arr.sum(axis=0)
# 각 열의 모든 행의 합

array([-2.3043, -0.0755,  1.6724,  1.0687])

In [ ]:
np.sum([0.9029,-1.3436, 0.7774, -1.4123, -1.2287])
# 첫 번째 열의 모든 행의 평균

-2.3043

In [ ]:
arr.sum(axis=1)
# 각 행의 모든 열의 합

array([-0.4274,  2.9176, -0.5624, -0.7776, -0.789 ])

In [ ]:
np.sum([0.9029, -1.6216, -0.1582,  0.4495])
# 첫 번째 행의 모든 열의 합

-0.4273999999999999

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()
# 누적합

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr.cumsum(axis=0)
# 열의 누적합

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [ ]:
arr.cumsum(axis=1)
# 행의 누적합

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

# 정렬

In [ ]:
arr = rng.standard_normal(6)
arr

array([-1.0794,  0.878 ,  0.2245, -0.5916,  0.2263,  0.6862])

In [ ]:
np.sort(arr)
# 정렬 = 오름차순

array([-1.0794, -0.5916,  0.2245,  0.2263,  0.6862,  0.878 ])

In [ ]:
arr
# 원본 그대로 = 복사본 반환

array([-1.0794,  0.878 ,  0.2245, -0.5916,  0.2263,  0.6862])

In [ ]:
np.sort(arr)[::-1]
# 정렬 = 내림차순

array([ 0.878 ,  0.6862,  0.2263,  0.2245, -0.5916, -1.0794])

In [ ]:
arr
# 원본 그대로 = 복사본 반환

array([-1.0794,  0.878 ,  0.2245, -0.5916,  0.2263,  0.6862])

In [ ]:
arr.sort()
# 정렬 = 오름차순

In [ ]:
arr
# 원본 변경 = 배열 자체를 정렬

array([-1.0794, -0.5916,  0.2245,  0.2263,  0.6862,  0.878 ])

In [ ]:
# 구조가 있는 배열
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [ ]:
arr = rng.standard_normal((5, 3))
arr

array([[-1.3678,  0.6489,  0.3611],
       [-1.9529,  2.3474,  0.9685],
       [-0.7594,  0.9022, -0.467 ],
       [-0.0607,  0.7888, -1.2567],
       [ 0.5759,  1.399 ,  1.3223]])

In [ ]:
arr.sort(axis=1)
arr
# 행의 값 정렬 = 좌에서 우로 정렬

array([[-1.3678,  0.3611,  0.6489],
       [-1.9529,  0.9685,  2.3474],
       [-0.7594, -0.467 ,  0.9022],
       [-1.2567, -0.0607,  0.7888],
       [ 0.5759,  1.3223,  1.399 ]])

In [ ]:
arr.sort(axis=0)
arr
# 열의 값 정렬 = 위에서 아래로 정렬

array([[-1.9529, -0.467 ,  0.6489],
       [-1.3678, -0.0607,  0.7888],
       [-1.2567,  0.3611,  0.9022],
       [-0.7594,  0.9685,  1.399 ],
       [ 0.5759,  1.3223,  2.3474]])

In [ ]:
np.sort(arr)[::-1]
# 열의 값 정렬을 반대로 = 아래에서 위로 정렬

array([[ 0.5759,  1.3223,  2.3474],
       [-0.7594,  0.9685,  1.399 ],
       [-1.2567,  0.3611,  0.9022],
       [-1.3678, -0.0607,  0.7888],
       [-1.9529, -0.467 ,  0.6489]])

# 선형대수

In [ ]:
x.dot(y)
# x 와 y 의 행렬 곱셈

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
np.dot(x, y)
# x 와 y 의 행렬 곱셈
# 2 * 3 dot 3 * 2 = 2 * 2
# 만나는 차원의 수가 같아야 함 => 3 = 3
# 같은 차원의 대응하는 값을 곱하여 모두 더하는 방식

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
print((1 * 6) + (2 * -1) + (3 * 8))
print((1 * 23) + (2 * 7) + (3 * 9))
print((4 * 6) + (5 * -1) + (6 * 8))
print((4 * 23) + (5 * 7) + (6 * 9))

28
64
67
181


In [ ]:
# 1 로 채워진 배열
np.ones(3)

array([1., 1., 1.])

In [ ]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
print(x.shape)
print(np.ones(3).shape)

(2, 3)
(3,)


In [ ]:
x @ np.ones(3)
# 2 * 3 @ 3 * 1 = 2 * 1 = 1차원 배열

array([ 6., 15.])

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
np.diag(x)
# 대각선 원소를 1차원 배열로 반환

array([1, 4])

In [ ]:
np.trace(x)
# 대각선의 합

5

In [ ]:
# 선형대수 함수
from numpy.linalg import inv
X = rng.standard_normal((2, 2))
X
# 정사각행렬

array([[ 1.5554, -1.2381],
       [-1.1962, -0.4291]])

In [ ]:
X.T

array([[ 1.5554, -1.1962],
       [-1.2381, -0.4291]])

In [ ]:
mat = X.T @ X
mat
# 정사각행렬 곱
# 2 * 2 @ 2 * 2 = 2 * 2

array([[ 3.85  , -1.4124],
       [-1.4124,  1.7172]])

In [ ]:
print((1.5554 * 1.5554) + (-1.1962 * -1.1962))

3.8501635999999997


In [ ]:
inv(mat)
# 정사각행렬의 역행렬 = 두 행렬을 곱하여 단위행렬이 되는 행렬
# 단위행렬 = 대각선 원소가 모두 1이고 다른 원소는 모두 0 인 행렬

array([[0.372, 0.306],
       [0.306, 0.834]])

In [ ]:
np.dot(mat, inv(mat))
# 정사각행렬과 정사각행렬의 역행렬을 곱하면 단위행렬

array([[ 1.,  0.],
       [-0.,  1.]])

In [ ]:
mat @ inv(mat)

array([[ 1.,  0.],
       [-0.,  1.]])

In [ ]:
np.identity(n = 2, dtype = float)
# 단위행렬 만들기

array([[1., 0.],
       [0., 1.]])

In [ ]:
from numpy.linalg import det
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
det(x)
# 행렬식 계산 = ad - bc

-2.0000000000000004

In [ ]:
(1 * 4) - (2 * 3)

-2